name: A workflow for the Hello Kordia file
on: push

jobs:
  build:
    name: Hello Kordia action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Shane"
